<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>katalonRunTimeEngineDownloadButton</name>
   <tag></tag>
   <elementGuidId>21c037b2-463b-4c8b-85eb-715b6246f1e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@data-trackid=&quot;download-kre&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@data-trackid=&quot;download-kre&quot;]</value>
      <webElementGuid>07a6383d-1148-478d-9dba-bb80e614a7e6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
